name: Java CI with Maven Demo

on:
  push:
    branches: [ "main" ]
 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build 
      run: mvn clean install
    
    - name: test
      run: mvn test
   
    - name: package   
      run: |
        mvn package
        ls target/
    - uses: actions/upload-artifact@v3
      with:
         name: package
         path: /home/runner/work/sample-java-app/sample-java-app/target/sample-0.0.1-SNAPSHOT.jar
 #   - name: Deploy on AWS EC2
 #     env:
  #        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}
  #        HOSTNAME: ${{ secrets.HOSTNAME  }}
  #        USER_NAME: ${{ secrets.USERNAME  }}
         
  #    run: |
  #       echo "$PRIVATE_KEY" > private_key.pem && chmod 600 private_key.pem
  #       ls -lrth
 #        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@13.127.44.56 
 #        scp -i private_key.pem /home/runner/work/sample-java-app/sample-java-app/target/sample-0.0.1-SNAPSHOT.jar ubuntu@13.127.44.56:/home/ubuntu/javafile
          
   

